### ISSUE TITLE
problem freeing buf, RuntimeError: overflowed buffer in push()

### ISSUE THREAD

**Issue by mmp3** [bottler/iisignature#18]
Minimal reproducible example:

```
import iisignature
iisignature.prepare(3, 4)
```

error message:

```
problem freeing buf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: overflowed buffer in push()
```

Version information:

```
iisignature.__version__
#  '0.24'
```

```
% python3 --version
# Python 3.10.7
```

on MacOs Monterey 12.3.1, M1

**Comment by bottler** [comment]
The compiled code for the logsignature is designed for x86, and there is no hope of it working on M1 processors. If you want to calculate log signatures right now, I suggest using `iisignature.prepare(3, 4, "O")` to force a simple calculation to happen (so that no compiled code is generated or needed). 

More detail:  When no method is specified, i.e. `iisignature.prepare(3, 4)`, it is understood that the default method is wanted, i.e. `iisignature.prepare(3, 4, "D")`. In small cases, the default method is to make compiled code, i.e. "C". It would be good to detect, perhaps with `#ifdef __arm__` that we have a non-x86 processor and change the default to be "O" in that case. Also to have a nice error message for trying to use the compiled code on M1.

**Comment by mmp3** [comment]
very clear. Thank you for the thorough explanation!
