### ISSUE TITLE
What if the points are complex?

### ISSUE THREAD

**Issue by creator2020A** [bottler/iisignature#9]
If the points are comples does this function return correct signature.

**Comment by bottler** [comment]
(For context, [see here](https://math.stackexchange.com/questions/2874431/help-in-numerical-verification-of-chens-identity-in-rough-path-theory/2882996) where it is suggested that the matlab example is being asked for and some conjugation is needed.)

I'm really curious as to the application here. What is the motivation for the signature of a complex path?

The main part of iisignature will not cope with complex numbers - you cannot call `iisignature.sig` or similar from python with an array of complex numbers in the current implementation. If you try you should get a slightly misleading and misspelled error message like `... must be (convertable to) a numpy array`.

But I think you are asking about the matlab signature code [here](https://github.com/bottler/iisignature/blob/master/examples/matlab/sig.m). I think it will just work with complex numbers because they do not require a special type in matlab. It will do the normal calculation. It does not do any complex conjugation. That would need to be added. But right now I don't know where you would want it.
